#!/bin/sh
# this line works with the MEX compiled
#octave -p "$SRC_DIR/matlabPyrTools/MEX" -p "$SRC_DIR/matlabPyrTools" -p "$SRC_DIR" --silent --eval "[im] = imread(\"$2\"); if (ndims(im) == 3) im=rgb2gray(im); end; [dm] = imread(\"$1\");if (ndims(dm) == 3) dm=rgb2gray(dm); end; printf(\"%f\n\",(iwssim(dm,im)))"
#PATH=`cwd`
SRC_DIR=`dirname $0`
octave  -p "$SRC_DIR/matlabPyrTools" -p "$SRC_DIR" --silent --eval "printf(\"%f\n\",(iwssim(rgb2gray(imread(\"$1\")), rgb2gray(imread(\"$2\")))))"
#octave --eval "a"
